# Data access via WFS from Python

In [1]:
import csv
import urllib2
import pandas as pd

# The URL to the collection (as comma-separated values).
collection_url = "http://geoserver-123.aodn.org.au/geoserver/ows?typeName=anmn_ctd_profiles_data&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=TIME%20%3E%3D%20'2016-01-01T00%3A00%3A00.000Z'"

# Fetch data...
response = urllib2.urlopen(collection_url)

# .. and read into a pandass DataFrame
df = pd.read_csv(response)

In [2]:
# Get a quick preview of what we got
df.head()

,FID,file_id,site_code,cruise_id,time_coverage_start,time_coverage_end,TIME,INSTANCE,DIRECTION,TIME_quality_control,...,TURB_quality_control,CHLF,CHLF_quality_control,CNDC,CNDC_quality_control,DESC,DESC_quality_control,DENS,DENS_quality_control,geom
0,anmn_ctd_profiles_data.fid--40252aaa_154ecea02...,974,NRSROT,3096,2016-02-23T01:28:49,2016-02-23T01:28:49,2016-02-23T01:28:49,NaN,D,NaN,...,0,NaN,NaN,5.0209,0,0.296,0,1025.0457,0,POINT (115.4166833333 -32.0000166667)
1,anmn_ctd_profiles_data.fid--40252aaa_154ecea02...,974,NRSROT,3096,2016-02-23T01:28:49,2016-02-23T01:28:49,2016-02-23T01:28:49,NaN,D,NaN,...,0,NaN,NaN,5.0209,0,0.379,0,1025.0503,0,POINT (115.4166833333 -32.0000166667)
2,anmn_ctd_profiles_data.fid--40252aaa_154ecea02...,974,NRSROT,3096,2016-02-23T01:28:49,2016-02-23T01:28:49,2016-02-23T01:28:49,NaN,D,NaN,...,0,NaN,NaN,5.0206,0,0.356,0,1025.0544,0,POINT (115.4166833333 -32.0000166667)
3,anmn_ctd_profiles_data.fid--40252aaa_154ecea02...,974,NRSROT,3096,2016-02-23T01:28:49,2016-02-23T01:28:49,2016-02-23T01:28:49,NaN,D,NaN,...,0,NaN,NaN,5.0206,0,0.325,0,1025.0598,0,POINT (115.4166833333 -32.0000166667)
4,anmn_ctd_profiles_data.fid--40252aaa_154ecea02...,974,NRSROT,3096,2016-02-23T01:28:49,2016-02-23T01:28:49,2016-02-23T01:28:49,NaN,D,NaN,...,0,NaN,NaN,5.0206,0,0.292,0,1025.0645,0,POINT (115.4166833333 -32.0000166667)

In [3]:
# A summary of the column properties
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 813 entries, 0 to 812
Data columns (total 37 columns):
FID                          813 non-null object
file_id                      813 non-null int64
site_code                    813 non-null object
cruise_id                    813 non-null object
time_coverage_start          813 non-null object
time_coverage_end            813 non-null object
TIME                         813 non-null object
INSTANCE                     0 non-null float64
DIRECTION                    813 non-null object
TIME_quality_control         0 non-null float64
LATITUDE                     813 non-null float64
LATITUDE_quality_control     0 non-null float64
LONGITUDE                    813 non-null float64
LONGITUDE_quality_control    0 non-null float64
DEPTH                        813 non-null float64
DEPTH_quality_control        0 non-null float64
BOT_DEPTH                    813 non-null int64
BOT_DEPTH_quality_control    0 non-null float64
PRES_REL                     807 non-null float64
PRES_REL_quality_control     813 non-null int64
TEMP                         806 non-null float64
TEMP_quality_control         813 non-null int64
PSAL                         806 non-null float64
PSAL_quality_control         813 non-null int64
DOX2                         681 non-null float64
DOX2_quality_control         692 non-null float64
TURB                         807 non-null float64
TURB_quality_control         813 non-null int64
CHLF                         0 non-null float64
CHLF_quality_control         0 non-null float64
CNDC                         807 non-null float64
CNDC_quality_control         813 non-null int64
DESC                         807 non-null float64
DESC_quality_control         813 non-null int64
DENS                         807 non-null float64
DENS_quality_control         813 non-null int64
geom                         813 non-null object
dtypes: float64(20), int64(9), object(8)
memory usage: 241.4+ KB

Done! Now we've got our data in here, all that's left to do is
* Analyse data
* Make plots
* Write the paper
* Celebrate!